# #1
Inductive reasoning is using specific observations to create a conclusion. An example could be Qdoba has been busy on Monday and Tuesday, therfore Qdoba will be busy on Wednesday. Deductive reasoning is when using general statements to create a specific theory. An example of deductive reasoning is all of the people in a club are at least 21 years old. A friend of yours is in the club. Therefore, your friend is at least 21 years old.

# #2

In [2]:
import numpy as np
import pandas as pd

cleveland_df = pd.read_csv("processed.cleveland.data")
cleveland_df.head(10)

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
0,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
1,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
2,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
3,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
4,56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
5,62.0,0.0,4.0,140.0,268.0,0.0,2.0,160.0,0.0,3.6,3.0,2.0,3.0,3
6,57.0,0.0,4.0,120.0,354.0,0.0,0.0,163.0,1.0,0.6,1.0,0.0,3.0,0
7,63.0,1.0,4.0,130.0,254.0,0.0,2.0,147.0,0.0,1.4,2.0,1.0,7.0,2
8,53.0,1.0,4.0,140.0,203.0,1.0,2.0,155.0,1.0,3.1,3.0,0.0,7.0,1
9,57.0,1.0,4.0,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,0

In [5]:
cleveland_df.rename(columns = {"63.0" : "Age", "1.0" : "Sex", "1.0.1" : "Chest Pain", "145.0" : "Restbp", 
                       "233.0" : "Chol", "1.0.2" : "FBS", "2.0" : "Restecg", "150.0" : "Maxhr", 
                       "0.0" : "Exang", "2.3" : "ST Depression", "3.0" : "Slope",  "0.0.1" : "Vessels", 
                       "6.0" : "Thal",  "0" : "Diagnosis"}, inplace = True)
cleveland_df.head()

,Age,Sex,Chest Pain,Restbp,Chol,FBS,Restecg,Maxhr,Exang,ST Depression,Slope,Vessels,Thal,Diagnosis
0,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
1,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
2,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
3,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
4,56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0